# Generated by Django 6.0.5 on 2026-08-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('english', models.TextField()),
                ('french', models.TextField()),
                ('context', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
