# Generated by Django 6.0.5 on 2026-08-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcoursedemand',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='historicalcoursedemand',
            constraint=models.UniqueConstraint(fields=('course', 'academic_year'), name='unique_historical_course_year'),
        ),
    ]
