# Generated by Django 6.0.5 on 2026-08-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('courses', '0001_initial'),
        ('people', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('default_weight', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CounselorConstraintPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.counselor')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constraints.softconstraint')),
            ],
            options={
                'ordering': ['counselor', 'constraint'],
            },
        ),
        migrations.CreateModel(
            name='CourseConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('course_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='courses.course')),
                ('course_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='courses.course')),
            ],
            options={
                'ordering': ['course_a', 'course_b'],
                'constraints': [models.UniqueConstraint(fields=('course_a', 'course_b'), name='unique_course_conflict'), models.CheckConstraint(condition=models.Q(('course_a', models.F('course_b')), _negated=True), name='course_cannot_conflict_with_itself')],
            },
        ),
        migrations.CreateModel(
            name='CourseRoomRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('science_lab', 'Science Lab'), ('computer_lab', 'Computer Lab'), ('gym', 'Gym'), ('dome', 'Dome'), ('art_room', 'Art Room'), ('music_room', 'Music Room')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'ordering': ['course', 'room_type'],
                'constraints': [models.UniqueConstraint(fields=('course', 'room_type'), name='unique_course_room_requirement')],
            },
        ),
        migrations.CreateModel(
            name='CourseQualificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constraints.qualification')),
            ],
            options={
                'ordering': ['course', 'qualification'],
                'constraints': [models.UniqueConstraint(fields=('course', 'qualification'), name='unique_course_qualification_requirement')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
            options={
                'ordering': ['teacher', 'timeslot'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'timeslot'), name='unique_teacher_availability')],
            },
        ),
        migrations.CreateModel(
            name='TeacherCoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
            ],
            options={
                'ordering': ['teacher', 'course'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'course'), name='unique_teacher_preference')],
            },
        ),
        migrations.CreateModel(
            name='TeacherCurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
            ],
            options={
                'ordering': ['teacher', 'academic_year', 'course'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'course', 'academic_year'), name='unique_teacher_current_course')],
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constraints.qualification')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
            ],
            options={
                'ordering': ['teacher', 'qualification'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'qualification'), name='unique_teacher_qualification')],
            },
        ),
    ]
