"""Stable API error codes owned by the scheduling domain."""

SECTION_PLANNING_APPROVAL_CONFLICT = "section_planning_approval_conflict"
SECTION_PLACEMENT_CONFLICT = "section_placement_conflict"
TEACHER_ASSIGNMENT_CONFLICT = "teacher_assignment_conflict"
STUDENT_ASSIGNMENT_CONFLICT = "student_assignment_conflict"

SCHEDULING_EXECUTION_IDEMPOTENCY_CONFLICT = "scheduling_execution_idempotency_conflict"
SCHEDULING_EXECUTION_ENQUEUE_FAILED = "scheduling_execution_enqueue_failed"
SCHEDULING_EXECUTION_WORKER_FAILED = "scheduling_execution_worker_failed"
SCHEDULING_EXECUTION_DOMAIN_FAILED = "scheduling_execution_domain_failed"

# These workflow codes reserve the next-release lock and rerun contract. They
# are intentionally separate from pure-engine diagnostics because services own
# authorization, current-state validation, and transactional workflow errors.
STUDENT_ASSIGNMENT_LOCK_INVALID_TARGET = "student_assignment_lock_invalid_target"
STUDENT_ASSIGNMENT_LOCK_FINAL_STAFFING_REQUIRED = "student_assignment_lock_final_staffing_required"
STUDENT_ASSIGNMENT_RERUN_SCOPE_INVALID = "student_assignment_rerun_scope_invalid"
STUDENT_ASSIGNMENT_RERUN_CONTEXT_CHANGED = "student_assignment_rerun_context_changed"
STUDENT_ASSIGNMENT_WHAT_IF_LOCK_NOT_ACTIVE = "student_assignment_what_if_lock_not_active"
STUDENT_ASSIGNMENT_SECTION_CANCELLATION_REQUIRES_RERUN = "student_assignment_section_cancellation_requires_rerun"

# Special-program workflow codes belong to services rather than the pure
# engine: they describe persisted configuration and lifecycle facts that a
# counselor can correct before a planning run is created.
ONLINE_SUPERVISION_CONFIGURATION_INVALID = "online_supervision_configuration_invalid"
ONLINE_SUPERVISION_PLAN_CONTEXT_CHANGED = "online_supervision_plan_context_changed"
ONLINE_SUPERVISION_SESSION_CANCELLATION_REQUIRES_RERUN = "online_supervision_session_cancellation_requires_rerun"
HALF_SEMESTER_PAIR_INVALID_CONFIGURATION = "half_semester_pair_invalid_configuration"
STUDENT_SPECIAL_COMMITMENT_LOCK_INVALID_TARGET = "student_special_commitment_lock_invalid_target"

ACTIVE_DELIVERY_GROUPS_CHANGED_SINCE_RUN = "active_delivery_groups_changed_since_run"
EXACT_BUDGET_TOTAL_MISMATCH = "exact_budget_total_mismatch"
SECTION_BUDGET_EXCEEDED = "section_budget_exceeded"
ADJUSTED_BUDGET_NO_LONGER_FEASIBLE = "adjusted_budget_no_longer_feasible"
BUDGET_RUN_ALREADY_APPROVED = "budget_run_already_approved"

COURSE_NO_LONGER_EXISTS = "course_no_longer_exists"
COURSE_OFFERING_NOT_ACTIVE = "course_offering_not_active"
COMBINED_OFFERING_REQUIRES_PHYSICAL_STAFFING_WORKFLOW = "combined_offering_requires_physical_staffing_workflow"
COURSE_NOT_ALLOWED_IN_SEMESTER_2 = "course_not_allowed_in_semester_2"
COURSE_NOT_ALLOWED_IN_SEMESTER_1 = "course_not_allowed_in_semester_1"
COURSE_ALREADY_APPROVED_FROM_RUN = "course_already_approved_from_run"
EXISTING_SECTIONS_FOR_COURSE_YEAR = "existing_sections_for_course_year"
NO_UNAPPROVED_COURSES_REMAINING = "no_unapproved_courses_remaining"

PROTECTED_SECTIONS_EXCEED_TARGET = "protected_sections_exceed_target"
RECONCILIATION_PREVIEW_STALE = "reconciliation_preview_stale"

EXISTING_SECTIONS_FOR_DELIVERY_GROUP = "existing_sections_for_delivery_group"
STAFFING_RUN_ALREADY_APPROVED = "staffing_run_already_approved"
LINKED_BUDGET_TOTAL_MUST_BE_PRESERVED = "linked_budget_total_must_be_preserved"
ADJUSTED_COUNTS_NOT_STAFFING_FEASIBLE = "adjusted_counts_not_staffing_feasible"
STAFFING_CONFIGURATION_CHANGED_SINCE_RUN = "staffing_configuration_changed_since_run"
