"""Planning, roster, backup, and section-lifecycle domain values."""

CAPACITY_PROFILE_SCOPE_SHARED = "shared"
CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC = "course_specific"
CAPACITY_PROFILE_SCOPE_CHOICES = (
    (CAPACITY_PROFILE_SCOPE_SHARED, "Shared"),
    (CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC, "Course specific"),
)

COURSE_PRIORITY_TIER_CORE = 1
COURSE_PRIORITY_TIER_PATHWAY = 2
COURSE_PRIORITY_TIER_COUNSELOR = 3
COURSE_PRIORITY_TIER_STANDARD = 4
COURSE_PRIORITY_TIER_CHOICES = (
    (COURSE_PRIORITY_TIER_CORE, "Core graduation requirement"),
    (COURSE_PRIORITY_TIER_PATHWAY, "Pathway-critical"),
    (COURSE_PRIORITY_TIER_COUNSELOR, "Counselor-designated priority"),
    (COURSE_PRIORITY_TIER_STANDARD, "Standard elective"),
)

SECTION_PLANNING_RUN_STATUS_COMPLETE = "complete"
SECTION_PLANNING_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLANNING_RUN_STATUS_FAILED = "failed"
SECTION_PLANNING_RUN_STATUS_CHOICES = (
    (SECTION_PLANNING_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLANNING_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLANNING_RUN_STATUS_FAILED, "Failed"),
)

# Placement has an additional useful review state: a partial result can explain
# what fits, but it is never eligible for approval.
SECTION_PLACEMENT_RUN_STATUS_COMPLETE = "complete"
SECTION_PLACEMENT_RUN_STATUS_PARTIAL = "partial"
SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLACEMENT_RUN_STATUS_FAILED = "failed"
SECTION_PLACEMENT_RUN_STATUS_CHOICES = (
    (SECTION_PLACEMENT_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLACEMENT_RUN_STATUS_PARTIAL, "Partial"),
    (SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLACEMENT_RUN_STATUS_FAILED, "Failed"),
)

# Teacher assignment uses the same review states as placement, but has its own
# names so a later stage can evolve without changing historical placement rows.
TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE = "complete"
TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL = "partial"
TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE = "infeasible"
TEACHER_ASSIGNMENT_RUN_STATUS_FAILED = "failed"
TEACHER_ASSIGNMENT_RUN_STATUS_CHOICES = (
    (TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE, "Complete"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL, "Partial"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_FAILED, "Failed"),
)

# Student assignment is deliberately its own immutable downstream workflow.
STUDENT_ASSIGNMENT_RUN_STATUS_COMPLETE = "complete"
STUDENT_ASSIGNMENT_RUN_STATUS_PARTIAL = "partial"
STUDENT_ASSIGNMENT_RUN_STATUS_INFEASIBLE = "infeasible"
STUDENT_ASSIGNMENT_RUN_STATUS_FAILED = "failed"
STUDENT_ASSIGNMENT_RUN_STATUS_CHOICES = (
    (STUDENT_ASSIGNMENT_RUN_STATUS_COMPLETE, "Complete"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_PARTIAL, "Partial"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_FAILED, "Failed"),
)

# Execution records describe delivery of a solve request. They are separate
# from immutable solver-result runs so a worker can update queued/running/
# failed state without mutating a reviewed business recommendation.
SCHEDULING_EXECUTION_STATUS_QUEUED = "queued"
SCHEDULING_EXECUTION_STATUS_RUNNING = "running"
SCHEDULING_EXECUTION_STATUS_COMPLETED = "completed"
SCHEDULING_EXECUTION_STATUS_FAILED = "failed"
SCHEDULING_EXECUTION_STATUS_CHOICES = (
    (SCHEDULING_EXECUTION_STATUS_QUEUED, "Queued"),
    (SCHEDULING_EXECUTION_STATUS_RUNNING, "Running"),
    (SCHEDULING_EXECUTION_STATUS_COMPLETED, "Completed"),
    (SCHEDULING_EXECUTION_STATUS_FAILED, "Failed"),
)

SCHEDULING_EXECUTION_OPERATION_SECTION_PLACEMENT = "section_placement"
SCHEDULING_EXECUTION_OPERATION_TEACHER_ASSIGNMENT = "teacher_assignment"
SCHEDULING_EXECUTION_OPERATION_STUDENT_ASSIGNMENT = "student_assignment"
SCHEDULING_EXECUTION_OPERATION_CHOICES = (
    (SCHEDULING_EXECUTION_OPERATION_SECTION_PLACEMENT, "Section placement"),
    (SCHEDULING_EXECUTION_OPERATION_TEACHER_ASSIGNMENT, "Teacher assignment"),
    (SCHEDULING_EXECUTION_OPERATION_STUDENT_ASSIGNMENT, "Student assignment"),
)

STUDENT_ASSIGNMENT_STAFFING_MODE_SECTIONS_ONLY = "sections_only"
STUDENT_ASSIGNMENT_STAFFING_MODE_PARTIAL_STAFFING = "partial_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_PROVISIONAL_STAFFING = "provisional_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_FINAL_STAFFING = "final_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_CHOICES = (
    (STUDENT_ASSIGNMENT_STAFFING_MODE_SECTIONS_ONLY, "Sections only"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_PARTIAL_STAFFING, "Partial staffing"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_PROVISIONAL_STAFFING, "Provisional staffing"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_FINAL_STAFFING, "Final staffing"),
)

# Versioned transport vocabulary for student-assignment objective semantics.
# The engine owns the mathematical implementation; these values are repeated
# here only so serializers and task payload handling stay on the Django side of
# the engine boundary.
STUDENT_ASSIGNMENT_OBJECTIVE_SEMANTICS_V1 = "v1"
STUDENT_ASSIGNMENT_OBJECTIVE_SEMANTICS_V2 = "v2"
STUDENT_ASSIGNMENT_OBJECTIVE_SEMANTICS_VERSIONS = (
    STUDENT_ASSIGNMENT_OBJECTIVE_SEMANTICS_V1,
    STUDENT_ASSIGNMENT_OBJECTIVE_SEMANTICS_V2,
)
STUDENT_ASSIGNMENT_CANONICAL_IMPORTANCE_MIN = 0
STUDENT_ASSIGNMENT_CANONICAL_IMPORTANCE_MAX = 10

# A full run has no accepted student-assignment baseline. A scoped run must
# point to the approval that represents the accepted schedule it may revise;
# the resolved IDs remain in the immutable input snapshot.
STUDENT_ASSIGNMENT_RUN_SCOPE_FULL = "full"
STUDENT_ASSIGNMENT_RUN_SCOPE_SCOPED = "scoped"
STUDENT_ASSIGNMENT_RUN_SCOPE_CHOICES = (
    (STUDENT_ASSIGNMENT_RUN_SCOPE_FULL, "Full student assignment"),
    (STUDENT_ASSIGNMENT_RUN_SCOPE_SCOPED, "Scoped student-assignment rerun"),
)

# This is the temporary effective default until the approved school-wide
# StudentAssignmentConfiguration model owns the setting.
STUDENT_ASSIGNMENT_DEFAULT_MAX_PRIORITY_REQUESTS = 100

# Rerun preservation is a counselor-facing label.  The engine receives the
# label and applies its bounded internal penalty; numeric weights never become
# part of the API or of an immutable run snapshot.
STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_NONE = "none"
STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_SLIGHT = "slight"
STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_MODERATE = "moderate"
STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_STRONG = "strong"
STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_CHOICES = (
    (STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_NONE, "None"),
    (STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_SLIGHT, "Slight"),
    (STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_MODERATE, "Moderate"),
    (STUDENT_ASSIGNMENT_SCHEDULE_PRESERVATION_STRONG, "Strong"),
)

# These values describe counselor decisions, not solver outcomes. Keeping them
# in the scheduling domain lets models, services, and future serializers share
# one stable vocabulary without putting workflow values in common/constants.py.
STUDENT_ASSIGNMENT_LOCK_TYPE_EXACT_SECTION = "exact_student_section"
STUDENT_ASSIGNMENT_LOCK_TYPE_WHOLE_SCHEDULE = "whole_student_schedule"
STUDENT_ASSIGNMENT_LOCK_TYPE_SECTION_ROSTER = "section_roster"
STUDENT_ASSIGNMENT_LOCK_TYPE_COURSE_ROSTER = "course_roster"
STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_GROUP = "student_group_same_section"
STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_TEACHER = "student_teacher_course"
STUDENT_ASSIGNMENT_LOCK_TYPE_CHOICES = (
    (STUDENT_ASSIGNMENT_LOCK_TYPE_EXACT_SECTION, "Exact student section"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_WHOLE_SCHEDULE, "Whole student schedule"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_SECTION_ROSTER, "Section roster"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_COURSE_ROSTER, "Course roster"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_GROUP, "Student group in one section"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_TEACHER, "Student and teacher for course"),
)

# These locks constrain student-time commitments that have no normal Section
# target.  They intentionally live beside, rather than inside, the existing
# enrollment/roster lock vocabulary so a fake section is never needed.
STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_STUDY_TIME = "study_time"
STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_ONLINE_SUPERVISION_TIME = "online_supervision_time"
STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_CO_OP_TIME = "co_op_time"
STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_FOCUS_SEMESTER = "focus_semester"
STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_CHOICES = (
    (STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_STUDY_TIME, "Study time"),
    (STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_ONLINE_SUPERVISION_TIME, "Online supervision time"),
    (STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_CO_OP_TIME, "Co-op time"),
    (STUDENT_SPECIAL_COMMITMENT_LOCK_TYPE_FOCUS_SEMESTER, "Focus semester"),
)

STUDENT_SPECIAL_COMMITMENT_LOCK_MODE_EXACT = "exact"
STUDENT_SPECIAL_COMMITMENT_LOCK_MODE_EXCLUDE = "exclude"
STUDENT_SPECIAL_COMMITMENT_LOCK_MODE_CHOICES = (
    (STUDENT_SPECIAL_COMMITMENT_LOCK_MODE_EXACT, "Exact required choice"),
    (STUDENT_SPECIAL_COMMITMENT_LOCK_MODE_EXCLUDE, "Excluded choice"),
)

CO_OP_BLOCK_PAIR_A_B = "a_b"
CO_OP_BLOCK_PAIR_C_D = "c_d"
CO_OP_BLOCK_PAIR_CHOICES = (
    (CO_OP_BLOCK_PAIR_A_B, "A + B"),
    (CO_OP_BLOCK_PAIR_C_D, "C + D"),
)

ONLINE_SUPERVISION_SESSION_LIFECYCLE_ACTIVE = "active"
ONLINE_SUPERVISION_SESSION_LIFECYCLE_RETIRED = "retired"
ONLINE_SUPERVISION_SESSION_LIFECYCLE_CHOICES = (
    (ONLINE_SUPERVISION_SESSION_LIFECYCLE_ACTIVE, "Active"),
    (ONLINE_SUPERVISION_SESSION_LIFECYCLE_RETIRED, "Retired"),
)

STUDENT_SCHEDULE_COMMITMENT_LIFECYCLE_ACTIVE = "active"
STUDENT_SCHEDULE_COMMITMENT_LIFECYCLE_HISTORICAL = "historical"
STUDENT_SCHEDULE_COMMITMENT_LIFECYCLE_CHOICES = (
    (STUDENT_SCHEDULE_COMMITMENT_LIFECYCLE_ACTIVE, "Active"),
    (STUDENT_SCHEDULE_COMMITMENT_LIFECYCLE_HISTORICAL, "Historical"),
)

STUDENT_SCHEDULE_COMMITMENT_KIND_STUDY = "study"
STUDENT_SCHEDULE_COMMITMENT_KIND_CO_OP = "co_op"
STUDENT_SCHEDULE_COMMITMENT_KIND_FOCUS = "focus"
STUDENT_SCHEDULE_COMMITMENT_KIND_CHOICES = (
    (STUDENT_SCHEDULE_COMMITMENT_KIND_STUDY, "Study"),
    (STUDENT_SCHEDULE_COMMITMENT_KIND_CO_OP, "Co-op"),
    (STUDENT_SCHEDULE_COMMITMENT_KIND_FOCUS, "Focus"),
)

SOFT_CONSTRAINT_IMPORTANCE_NOT_IMPORTANT = "not_important"
SOFT_CONSTRAINT_IMPORTANCE_A_LITTLE_BIT_IMPORTANT = "a_little_bit_important"
SOFT_CONSTRAINT_IMPORTANCE_IMPORTANT = "important"
SOFT_CONSTRAINT_IMPORTANCE_REALLY_IMPORTANT = "really_important"
SOFT_CONSTRAINT_IMPORTANCE_EXTREMELY_IMPORTANT = "extremely_important"
SOFT_CONSTRAINT_IMPORTANCE_CHOICES = (
    (SOFT_CONSTRAINT_IMPORTANCE_NOT_IMPORTANT, "Not important"),
    (SOFT_CONSTRAINT_IMPORTANCE_A_LITTLE_BIT_IMPORTANT, "A little bit important"),
    (SOFT_CONSTRAINT_IMPORTANCE_IMPORTANT, "Important"),
    (SOFT_CONSTRAINT_IMPORTANCE_REALLY_IMPORTANT, "Really important"),
    (SOFT_CONSTRAINT_IMPORTANCE_EXTREMELY_IMPORTANT, "Extremely important"),
)

STUDENT_ASSIGNMENT_BASIS_PRIMARY_REQUEST = "primary_request"
STUDENT_ASSIGNMENT_BASIS_APPROVED_BACKUP = "approved_backup"
STUDENT_ASSIGNMENT_BASIS_CHOICES = (
    (STUDENT_ASSIGNMENT_BASIS_PRIMARY_REQUEST, "Primary request"),
    (STUDENT_ASSIGNMENT_BASIS_APPROVED_BACKUP, "Approved backup"),
)

TEACHER_TIME_PREFERENCE_PREFERRED = "preferred"
TEACHER_TIME_PREFERENCE_AVOID = "avoid"
TEACHER_TIME_PREFERENCE_CHOICES = (
    (TEACHER_TIME_PREFERENCE_PREFERRED, "Preferred"),
    (TEACHER_TIME_PREFERENCE_AVOID, "Avoid when possible"),
)

SECTION_PLACEMENT_INPUT_FIXED_SEMESTER = "fixed_semester"
SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL = "annual_total"
SECTION_PLACEMENT_INPUT_MODE_CHOICES = (
    (SECTION_PLACEMENT_INPUT_FIXED_SEMESTER, "Existing fixed-semester sections"),
    (SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL, "Approved annual section totals"),
)

# Operational section lifecycle. Retired sections remain stored for audit but
# are excluded from active planning, placement, staffing, and enrollment work.
SECTION_LIFECYCLE_ACTIVE = "active"
SECTION_LIFECYCLE_RETIRED = "retired"
SECTION_LIFECYCLE_CHOICES = (
    (SECTION_LIFECYCLE_ACTIVE, "Active"),
    (SECTION_LIFECYCLE_RETIRED, "Retired"),
)

SECTION_RECONCILIATION_ACTION_KEPT = "kept"
SECTION_RECONCILIATION_ACTION_CREATED = "created"
SECTION_RECONCILIATION_ACTION_MOVED = "moved"
SECTION_RECONCILIATION_ACTION_RETIRED = "retired"
SECTION_RECONCILIATION_ACTION_REACTIVATED = "reactivated"
SECTION_RECONCILIATION_ACTION_CHOICES = (
    (SECTION_RECONCILIATION_ACTION_KEPT, "Kept"),
    (SECTION_RECONCILIATION_ACTION_CREATED, "Created"),
    (SECTION_RECONCILIATION_ACTION_MOVED, "Moved"),
    (SECTION_RECONCILIATION_ACTION_RETIRED, "Retired"),
    (SECTION_RECONCILIATION_ACTION_REACTIVATED, "Reactivated"),
)

SECTION_BUDGET_EXACT = "exact"
SECTION_BUDGET_CEILING = "ceiling"
SECTION_BUDGET_TYPE_CHOICES = (
    (SECTION_BUDGET_EXACT, "Exact physical-section total"),
    (SECTION_BUDGET_CEILING, "Maximum physical-section total"),
)

BACKUP_POLICY_PROMOTE_AVAILABLE = "promote_available"
BACKUP_POLICY_IGNORE = "ignore"
BACKUP_POLICY_CHOICES = (
    (BACKUP_POLICY_PROMOTE_AVAILABLE, "Promote available backups"),
    (BACKUP_POLICY_IGNORE, "Ignore backups"),
)

TEACHER_ROSTER_STATUS_DRAFT = "draft"
TEACHER_ROSTER_STATUS_READY = "ready"
TEACHER_ROSTER_STATUS_CHOICES = (
    (TEACHER_ROSTER_STATUS_DRAFT, "Draft"),
    (TEACHER_ROSTER_STATUS_READY, "Ready"),
)
