"""Planning, roster, backup, and section-lifecycle domain values."""

CAPACITY_PROFILE_SCOPE_SHARED = "shared"
CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC = "course_specific"
CAPACITY_PROFILE_SCOPE_CHOICES = (
    (CAPACITY_PROFILE_SCOPE_SHARED, "Shared"),
    (CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC, "Course specific"),
)

COURSE_PRIORITY_TIER_CORE = 1
COURSE_PRIORITY_TIER_PATHWAY = 2
COURSE_PRIORITY_TIER_COUNSELOR = 3
COURSE_PRIORITY_TIER_STANDARD = 4
COURSE_PRIORITY_TIER_CHOICES = (
    (COURSE_PRIORITY_TIER_CORE, "Core graduation requirement"),
    (COURSE_PRIORITY_TIER_PATHWAY, "Pathway-critical"),
    (COURSE_PRIORITY_TIER_COUNSELOR, "Counselor-designated priority"),
    (COURSE_PRIORITY_TIER_STANDARD, "Standard elective"),
)

SECTION_PLANNING_RUN_STATUS_COMPLETE = "complete"
SECTION_PLANNING_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLANNING_RUN_STATUS_FAILED = "failed"
SECTION_PLANNING_RUN_STATUS_CHOICES = (
    (SECTION_PLANNING_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLANNING_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLANNING_RUN_STATUS_FAILED, "Failed"),
)

# Placement has an additional useful review state: a partial result can explain
# what fits, but it is never eligible for approval.
SECTION_PLACEMENT_RUN_STATUS_COMPLETE = "complete"
SECTION_PLACEMENT_RUN_STATUS_PARTIAL = "partial"
SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLACEMENT_RUN_STATUS_FAILED = "failed"
SECTION_PLACEMENT_RUN_STATUS_CHOICES = (
    (SECTION_PLACEMENT_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLACEMENT_RUN_STATUS_PARTIAL, "Partial"),
    (SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLACEMENT_RUN_STATUS_FAILED, "Failed"),
)

# Teacher assignment uses the same review states as placement, but has its own
# names so a later stage can evolve without changing historical placement rows.
TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE = "complete"
TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL = "partial"
TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE = "infeasible"
TEACHER_ASSIGNMENT_RUN_STATUS_FAILED = "failed"
TEACHER_ASSIGNMENT_RUN_STATUS_CHOICES = (
    (TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE, "Complete"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL, "Partial"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_FAILED, "Failed"),
)

TEACHER_TIME_PREFERENCE_PREFERRED = "preferred"
TEACHER_TIME_PREFERENCE_AVOID = "avoid"
TEACHER_TIME_PREFERENCE_CHOICES = (
    (TEACHER_TIME_PREFERENCE_PREFERRED, "Preferred"),
    (TEACHER_TIME_PREFERENCE_AVOID, "Avoid when possible"),
)

SECTION_PLACEMENT_INPUT_FIXED_SEMESTER = "fixed_semester"
SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL = "annual_total"
SECTION_PLACEMENT_INPUT_MODE_CHOICES = (
    (SECTION_PLACEMENT_INPUT_FIXED_SEMESTER, "Existing fixed-semester sections"),
    (SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL, "Approved annual section totals"),
)

# Operational section lifecycle. Retired sections remain stored for audit but
# are excluded from active planning, placement, staffing, and enrollment work.
SECTION_LIFECYCLE_ACTIVE = "active"
SECTION_LIFECYCLE_RETIRED = "retired"
SECTION_LIFECYCLE_CHOICES = (
    (SECTION_LIFECYCLE_ACTIVE, "Active"),
    (SECTION_LIFECYCLE_RETIRED, "Retired"),
)

SECTION_RECONCILIATION_ACTION_KEPT = "kept"
SECTION_RECONCILIATION_ACTION_CREATED = "created"
SECTION_RECONCILIATION_ACTION_MOVED = "moved"
SECTION_RECONCILIATION_ACTION_RETIRED = "retired"
SECTION_RECONCILIATION_ACTION_REACTIVATED = "reactivated"
SECTION_RECONCILIATION_ACTION_CHOICES = (
    (SECTION_RECONCILIATION_ACTION_KEPT, "Kept"),
    (SECTION_RECONCILIATION_ACTION_CREATED, "Created"),
    (SECTION_RECONCILIATION_ACTION_MOVED, "Moved"),
    (SECTION_RECONCILIATION_ACTION_RETIRED, "Retired"),
    (SECTION_RECONCILIATION_ACTION_REACTIVATED, "Reactivated"),
)

SECTION_BUDGET_EXACT = "exact"
SECTION_BUDGET_CEILING = "ceiling"
SECTION_BUDGET_TYPE_CHOICES = (
    (SECTION_BUDGET_EXACT, "Exact physical-section total"),
    (SECTION_BUDGET_CEILING, "Maximum physical-section total"),
)

BACKUP_POLICY_PROMOTE_AVAILABLE = "promote_available"
BACKUP_POLICY_IGNORE = "ignore"
BACKUP_POLICY_CHOICES = (
    (BACKUP_POLICY_PROMOTE_AVAILABLE, "Promote available backups"),
    (BACKUP_POLICY_IGNORE, "Ignore backups"),
)

TEACHER_ROSTER_STATUS_DRAFT = "draft"
TEACHER_ROSTER_STATUS_READY = "ready"
TEACHER_ROSTER_STATUS_CHOICES = (
    (TEACHER_ROSTER_STATUS_DRAFT, "Draft"),
    (TEACHER_ROSTER_STATUS_READY, "Ready"),
)
