"""Planning, roster, backup, and section-lifecycle domain values."""

CAPACITY_PROFILE_SCOPE_SHARED = "shared"
CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC = "course_specific"
CAPACITY_PROFILE_SCOPE_CHOICES = (
    (CAPACITY_PROFILE_SCOPE_SHARED, "Shared"),
    (CAPACITY_PROFILE_SCOPE_COURSE_SPECIFIC, "Course specific"),
)

COURSE_PRIORITY_TIER_CORE = 1
COURSE_PRIORITY_TIER_PATHWAY = 2
COURSE_PRIORITY_TIER_COUNSELOR = 3
COURSE_PRIORITY_TIER_STANDARD = 4
COURSE_PRIORITY_TIER_CHOICES = (
    (COURSE_PRIORITY_TIER_CORE, "Core graduation requirement"),
    (COURSE_PRIORITY_TIER_PATHWAY, "Pathway-critical"),
    (COURSE_PRIORITY_TIER_COUNSELOR, "Counselor-designated priority"),
    (COURSE_PRIORITY_TIER_STANDARD, "Standard elective"),
)

SECTION_PLANNING_RUN_STATUS_COMPLETE = "complete"
SECTION_PLANNING_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLANNING_RUN_STATUS_FAILED = "failed"
SECTION_PLANNING_RUN_STATUS_CHOICES = (
    (SECTION_PLANNING_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLANNING_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLANNING_RUN_STATUS_FAILED, "Failed"),
)

# Placement has an additional useful review state: a partial result can explain
# what fits, but it is never eligible for approval.
SECTION_PLACEMENT_RUN_STATUS_COMPLETE = "complete"
SECTION_PLACEMENT_RUN_STATUS_PARTIAL = "partial"
SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE = "infeasible"
SECTION_PLACEMENT_RUN_STATUS_FAILED = "failed"
SECTION_PLACEMENT_RUN_STATUS_CHOICES = (
    (SECTION_PLACEMENT_RUN_STATUS_COMPLETE, "Complete"),
    (SECTION_PLACEMENT_RUN_STATUS_PARTIAL, "Partial"),
    (SECTION_PLACEMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (SECTION_PLACEMENT_RUN_STATUS_FAILED, "Failed"),
)

# Teacher assignment uses the same review states as placement, but has its own
# names so a later stage can evolve without changing historical placement rows.
TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE = "complete"
TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL = "partial"
TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE = "infeasible"
TEACHER_ASSIGNMENT_RUN_STATUS_FAILED = "failed"
TEACHER_ASSIGNMENT_RUN_STATUS_CHOICES = (
    (TEACHER_ASSIGNMENT_RUN_STATUS_COMPLETE, "Complete"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_PARTIAL, "Partial"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (TEACHER_ASSIGNMENT_RUN_STATUS_FAILED, "Failed"),
)

# Student assignment is deliberately its own immutable downstream workflow.
STUDENT_ASSIGNMENT_RUN_STATUS_COMPLETE = "complete"
STUDENT_ASSIGNMENT_RUN_STATUS_PARTIAL = "partial"
STUDENT_ASSIGNMENT_RUN_STATUS_INFEASIBLE = "infeasible"
STUDENT_ASSIGNMENT_RUN_STATUS_FAILED = "failed"
STUDENT_ASSIGNMENT_RUN_STATUS_CHOICES = (
    (STUDENT_ASSIGNMENT_RUN_STATUS_COMPLETE, "Complete"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_PARTIAL, "Partial"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_INFEASIBLE, "Infeasible"),
    (STUDENT_ASSIGNMENT_RUN_STATUS_FAILED, "Failed"),
)

STUDENT_ASSIGNMENT_STAFFING_MODE_SECTIONS_ONLY = "sections_only"
STUDENT_ASSIGNMENT_STAFFING_MODE_PARTIAL_STAFFING = "partial_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_PROVISIONAL_STAFFING = "provisional_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_FINAL_STAFFING = "final_staffing"
STUDENT_ASSIGNMENT_STAFFING_MODE_CHOICES = (
    (STUDENT_ASSIGNMENT_STAFFING_MODE_SECTIONS_ONLY, "Sections only"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_PARTIAL_STAFFING, "Partial staffing"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_PROVISIONAL_STAFFING, "Provisional staffing"),
    (STUDENT_ASSIGNMENT_STAFFING_MODE_FINAL_STAFFING, "Final staffing"),
)

# A full run has no accepted student-assignment baseline. A scoped run must
# point to the approval that represents the accepted schedule it may revise;
# the resolved IDs remain in the immutable input snapshot.
STUDENT_ASSIGNMENT_RUN_SCOPE_FULL = "full"
STUDENT_ASSIGNMENT_RUN_SCOPE_SCOPED = "scoped"
STUDENT_ASSIGNMENT_RUN_SCOPE_CHOICES = (
    (STUDENT_ASSIGNMENT_RUN_SCOPE_FULL, "Full student assignment"),
    (STUDENT_ASSIGNMENT_RUN_SCOPE_SCOPED, "Scoped student-assignment rerun"),
)

# These values describe counselor decisions, not solver outcomes. Keeping them
# in the scheduling domain lets models, services, and future serializers share
# one stable vocabulary without putting workflow values in common/constants.py.
STUDENT_ASSIGNMENT_LOCK_TYPE_EXACT_SECTION = "exact_student_section"
STUDENT_ASSIGNMENT_LOCK_TYPE_WHOLE_SCHEDULE = "whole_student_schedule"
STUDENT_ASSIGNMENT_LOCK_TYPE_SECTION_ROSTER = "section_roster"
STUDENT_ASSIGNMENT_LOCK_TYPE_COURSE_ROSTER = "course_roster"
STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_GROUP = "student_group_same_section"
STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_TEACHER = "student_teacher_course"
STUDENT_ASSIGNMENT_LOCK_TYPE_CHOICES = (
    (STUDENT_ASSIGNMENT_LOCK_TYPE_EXACT_SECTION, "Exact student section"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_WHOLE_SCHEDULE, "Whole student schedule"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_SECTION_ROSTER, "Section roster"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_COURSE_ROSTER, "Course roster"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_GROUP, "Student group in one section"),
    (STUDENT_ASSIGNMENT_LOCK_TYPE_STUDENT_TEACHER, "Student and teacher for course"),
)

SOFT_CONSTRAINT_IMPORTANCE_NOT_IMPORTANT = "not_important"
SOFT_CONSTRAINT_IMPORTANCE_A_LITTLE_BIT_IMPORTANT = "a_little_bit_important"
SOFT_CONSTRAINT_IMPORTANCE_IMPORTANT = "important"
SOFT_CONSTRAINT_IMPORTANCE_REALLY_IMPORTANT = "really_important"
SOFT_CONSTRAINT_IMPORTANCE_EXTREMELY_IMPORTANT = "extremely_important"
SOFT_CONSTRAINT_IMPORTANCE_CHOICES = (
    (SOFT_CONSTRAINT_IMPORTANCE_NOT_IMPORTANT, "Not important"),
    (SOFT_CONSTRAINT_IMPORTANCE_A_LITTLE_BIT_IMPORTANT, "A little bit important"),
    (SOFT_CONSTRAINT_IMPORTANCE_IMPORTANT, "Important"),
    (SOFT_CONSTRAINT_IMPORTANCE_REALLY_IMPORTANT, "Really important"),
    (SOFT_CONSTRAINT_IMPORTANCE_EXTREMELY_IMPORTANT, "Extremely important"),
)

STUDENT_ASSIGNMENT_BASIS_PRIMARY_REQUEST = "primary_request"
STUDENT_ASSIGNMENT_BASIS_APPROVED_BACKUP = "approved_backup"
STUDENT_ASSIGNMENT_BASIS_CHOICES = (
    (STUDENT_ASSIGNMENT_BASIS_PRIMARY_REQUEST, "Primary request"),
    (STUDENT_ASSIGNMENT_BASIS_APPROVED_BACKUP, "Approved backup"),
)

TEACHER_TIME_PREFERENCE_PREFERRED = "preferred"
TEACHER_TIME_PREFERENCE_AVOID = "avoid"
TEACHER_TIME_PREFERENCE_CHOICES = (
    (TEACHER_TIME_PREFERENCE_PREFERRED, "Preferred"),
    (TEACHER_TIME_PREFERENCE_AVOID, "Avoid when possible"),
)

SECTION_PLACEMENT_INPUT_FIXED_SEMESTER = "fixed_semester"
SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL = "annual_total"
SECTION_PLACEMENT_INPUT_MODE_CHOICES = (
    (SECTION_PLACEMENT_INPUT_FIXED_SEMESTER, "Existing fixed-semester sections"),
    (SECTION_PLACEMENT_INPUT_ANNUAL_TOTAL, "Approved annual section totals"),
)

# Operational section lifecycle. Retired sections remain stored for audit but
# are excluded from active planning, placement, staffing, and enrollment work.
SECTION_LIFECYCLE_ACTIVE = "active"
SECTION_LIFECYCLE_RETIRED = "retired"
SECTION_LIFECYCLE_CHOICES = (
    (SECTION_LIFECYCLE_ACTIVE, "Active"),
    (SECTION_LIFECYCLE_RETIRED, "Retired"),
)

SECTION_RECONCILIATION_ACTION_KEPT = "kept"
SECTION_RECONCILIATION_ACTION_CREATED = "created"
SECTION_RECONCILIATION_ACTION_MOVED = "moved"
SECTION_RECONCILIATION_ACTION_RETIRED = "retired"
SECTION_RECONCILIATION_ACTION_REACTIVATED = "reactivated"
SECTION_RECONCILIATION_ACTION_CHOICES = (
    (SECTION_RECONCILIATION_ACTION_KEPT, "Kept"),
    (SECTION_RECONCILIATION_ACTION_CREATED, "Created"),
    (SECTION_RECONCILIATION_ACTION_MOVED, "Moved"),
    (SECTION_RECONCILIATION_ACTION_RETIRED, "Retired"),
    (SECTION_RECONCILIATION_ACTION_REACTIVATED, "Reactivated"),
)

SECTION_BUDGET_EXACT = "exact"
SECTION_BUDGET_CEILING = "ceiling"
SECTION_BUDGET_TYPE_CHOICES = (
    (SECTION_BUDGET_EXACT, "Exact physical-section total"),
    (SECTION_BUDGET_CEILING, "Maximum physical-section total"),
)

BACKUP_POLICY_PROMOTE_AVAILABLE = "promote_available"
BACKUP_POLICY_IGNORE = "ignore"
BACKUP_POLICY_CHOICES = (
    (BACKUP_POLICY_PROMOTE_AVAILABLE, "Promote available backups"),
    (BACKUP_POLICY_IGNORE, "Ignore backups"),
)

TEACHER_ROSTER_STATUS_DRAFT = "draft"
TEACHER_ROSTER_STATUS_READY = "ready"
TEACHER_ROSTER_STATUS_CHOICES = (
    (TEACHER_ROSTER_STATUS_DRAFT, "Draft"),
    (TEACHER_ROSTER_STATUS_READY, "Ready"),
)
