# Generated by Django 6.0.5 on 2026-08-05 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade_level', models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('language', 'Language'), ('technology', 'Technology'), ('arts', 'Arts'), ('business', 'Business'), ('humanities', 'Humanities')], max_length=50)),
                ('capacity_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('semester', models.IntegerField(choices=[(1, 'Fall'), (2, 'Winter')])),
                ('capacity_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_locked', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'course', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
            ],
            options={
                'ordering': ['student', 'section'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'prerequisite'],
                'constraints': [models.UniqueConstraint(fields=('course', 'prerequisite'), name='unique_course_prerequisite')],
            },
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('primary', 'Primary'), ('alternate', 'Alternate')], max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
            ],
            options={
                'ordering': ['academic_year', 'student', 'request_type', 'course'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'academic_year'), name='unique_student_course_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'section_number', 'academic_year'), name='unique_course_section_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section_enrollment'),
        ),
    ]
