"""Application role values owned by the people/identity domain."""

USER_ROLE_STUDENT = "student"
USER_ROLE_STUDENT_LABEL = "Student"
USER_ROLE_TEACHER = "teacher"
USER_ROLE_TEACHER_LABEL = "Teacher"
USER_ROLE_COUNSELOR = "counselor"
USER_ROLE_COUNSELOR_LABEL = "Counselor"
USER_ROLE_STAFF = "staff"
USER_ROLE_STAFF_LABEL = "Staff"
USER_ROLE_DIRECTOR = "director"
USER_ROLE_DIRECTOR_LABEL = "Director"
USER_ROLE_UNKNOWN = "unknown"
USER_ROLE_UNKNOWN_LABEL = "Unknown"
USER_ROLE_CHOICES = (
    (USER_ROLE_STUDENT, USER_ROLE_STUDENT_LABEL),
    (USER_ROLE_TEACHER, USER_ROLE_TEACHER_LABEL),
    (USER_ROLE_COUNSELOR, USER_ROLE_COUNSELOR_LABEL),
    (USER_ROLE_STAFF, USER_ROLE_STAFF_LABEL),
    (USER_ROLE_DIRECTOR, USER_ROLE_DIRECTOR_LABEL),
    (USER_ROLE_UNKNOWN, USER_ROLE_UNKNOWN_LABEL),
)

