"""Stable diagnostic codes emitted by pure scheduling solvers.

Messages may change as counselor wording improves; these codes are the durable
contract for tests, APIs, and future frontend behavior.
"""

BELOW_HARD_MIN_REVIEW_REQUIRED = "below_hard_min_review_required"
BUDGET_SEMESTER_SPLIT_INFEASIBLE = "budget_semester_split_infeasible"
COMBINED_OFFERING_OVER_CAPACITY = "combined_offering_over_capacity"
COMBINED_STAFFING_CONSTRAINTS_INFEASIBLE = "combined_staffing_constraints_infeasible"
COURSE_CONSTRAINT_NO_CANDIDATE = "course_constraint_no_candidate"
COURSE_STAFFING_CAPACITY_SHORTFALL = "course_staffing_capacity_shortfall"
NO_ELIGIBLE_TEACHER_FOR_DELIVERY_GROUP = "no_eligible_teacher_for_delivery_group"
NO_ELIGIBLE_TEACHERS = "no_eligible_teachers"
OFFERING_CONSTRAINT_NO_CANDIDATE = "offering_constraint_no_candidate"
OFFERING_SEMESTER_CONSTRAINT_NO_CANDIDATE = "offering_semester_constraint_no_candidate"
SECTION_BUDGET_INFEASIBLE = "section_budget_infeasible"
SEMESTER_CAPACITY_CHANGED_ANNUAL_PLAN = "semester_capacity_changed_annual_plan"
SEMESTER_STAFFING_CAPACITY_SHORTFALL = "semester_staffing_capacity_shortfall"
SHARED_QUALIFIED_STAFFING_POOL_INFEASIBLE = "shared_qualified_staffing_pool_infeasible"
STAFFING_CHANGED_DEMAND_PLAN = "staffing_changed_demand_plan"
TOTAL_STAFFING_CAPACITY_SHORTFALL = "total_staffing_capacity_shortfall"
UNMET_DEMAND_AFTER_STAFFING = "unmet_demand_after_staffing"

# Semester/A-D placement diagnostics. These are stable API/UI contract values;
# detailed wording remains a backend concern and can improve without breaking a
# counselor dashboard.
MISSING_CONFLICT_MATRIX = "missing_conflict_matrix"
ANNUAL_LOCK_OUTSIDE_ANNUAL_COUNT = "annual_lock_outside_annual_count"
LOCKED_TIMESLOT_OUTSIDE_YEAR_OR_SEMESTER = "locked_timeslot_outside_year_or_semester"
SECTION_LOCKED_WITHOUT_USABLE_TIMING = "section_locked_without_usable_timing"
NO_LEGAL_SEMESTER = "no_legal_semester"
NO_AVAILABLE_TIMESLOT = "no_available_timeslot"
NO_ELIGIBLE_TEACHER = "no_eligible_teacher"
TEACHER_AVAILABILITY_COLLISION = "teacher_availability_collision"
TEACHER_SEMESTER_OR_ANNUAL_CAPACITY_SHORTAGE = "teacher_semester_or_annual_capacity_shortage"
NO_COMPLETE_PLACEMENT = "no_complete_placement"

# Named teacher assignment diagnostics are stable API codes.  Views may change
# explanatory prose without forcing frontend clients to parse English text.
MISSING_ACCEPTED_PLACEMENT = "missing_accepted_placement"
NO_ELIGIBLE_TEACHER_FOR_SECTION = "no_eligible_teacher_for_section"
LOCKED_TEACHER_UNAVAILABLE = "locked_teacher_unavailable"
LOCKED_TEACHER_INELIGIBLE = "locked_teacher_ineligible"
TEACHER_TIMESLOT_COLLISION = "teacher_timeslot_collision"
TEACHER_SEMESTER_CAPACITY_SHORTAGE = "teacher_semester_capacity_shortage"
TEACHER_ANNUAL_CAPACITY_SHORTAGE = "teacher_annual_capacity_shortage"
TEACHER_COURSE_RULE_INFEASIBLE = "teacher_course_rule_infeasible"
NO_COMPLETE_TEACHER_ASSIGNMENT = "no_complete_teacher_assignment"
TEACHER_ASSIGNMENT_INPUT_CHANGED_SINCE_RUN = "teacher_assignment_input_changed_since_run"
TEACHER_ASSIGNMENT_FIXED_CONTEXT_CHANGED_SINCE_RUN = "teacher_assignment_fixed_context_changed_since_run"
FIXED_CONTEXT_CHANGED_SINCE_RUN = "fixed_context_changed_since_run"
PLACEMENT_INPUT_CHANGED_SINCE_RUN = "placement_input_changed_since_run"

# Student assignment diagnostics.  These are machine-readable planning facts,
# not counselor-facing English copy.
STUDENT_ASSIGNMENT_MISSING_ACCEPTED_PLACEMENT = "student_assignment_missing_accepted_placement"
STUDENT_ASSIGNMENT_INVALID_SECTION_CONTEXT = "student_assignment_invalid_section_context"
STUDENT_ASSIGNMENT_NO_ELIGIBLE_SECTION = "student_assignment_no_eligible_section"
STUDENT_ASSIGNMENT_SECTION_CAPACITY_EXHAUSTED = "student_assignment_section_capacity_exhausted"
STUDENT_ASSIGNMENT_TIMESLOT_COLLISION = "student_assignment_timeslot_collision"
STUDENT_ASSIGNMENT_COMBINED_SECTION_COLLISION = "student_assignment_combined_section_collision"
STUDENT_ASSIGNMENT_HARD_PREREQUISITE_CYCLE = "student_assignment_hard_prerequisite_cycle"
STUDENT_ASSIGNMENT_HARD_PREREQUISITE_SEQUENCE_UNAVAILABLE = "student_assignment_hard_prerequisite_sequence_unavailable"
STUDENT_ASSIGNMENT_UNRESOLVED_REQUIRED_REQUEST = "student_assignment_unresolved_required_request"
STUDENT_ASSIGNMENT_AMBIGUOUS_BACKUP_RESOLUTION = "student_assignment_ambiguous_backup_resolution"
STUDENT_ASSIGNMENT_LEGACY_ENROLLMENT_AMBIGUOUS = "student_assignment_legacy_enrollment_ambiguous"
STUDENT_ASSIGNMENT_INPUT_CHANGED_SINCE_RUN = "student_assignment_input_changed_since_run"
STUDENT_ASSIGNMENT_STAFFING_CONTEXT_CHANGED_SINCE_RUN = "student_assignment_staffing_context_changed_since_run"
STUDENT_ASSIGNMENT_INVALID_PROVISIONAL_STAFFING = "student_assignment_invalid_provisional_staffing"
NO_COMPLETE_STUDENT_ASSIGNMENT = "no_complete_student_assignment"
