"""Stable diagnostic codes emitted by pure scheduling solvers.

Messages may change as counselor wording improves; these codes are the durable
contract for tests, APIs, and future frontend behavior.
"""

BELOW_HARD_MIN_REVIEW_REQUIRED = "below_hard_min_review_required"
BUDGET_SEMESTER_SPLIT_INFEASIBLE = "budget_semester_split_infeasible"
COMBINED_OFFERING_OVER_CAPACITY = "combined_offering_over_capacity"
COMBINED_STAFFING_CONSTRAINTS_INFEASIBLE = "combined_staffing_constraints_infeasible"
COURSE_CONSTRAINT_NO_CANDIDATE = "course_constraint_no_candidate"
COURSE_STAFFING_CAPACITY_SHORTFALL = "course_staffing_capacity_shortfall"
NO_ELIGIBLE_TEACHER_FOR_DELIVERY_GROUP = "no_eligible_teacher_for_delivery_group"
NO_ELIGIBLE_TEACHERS = "no_eligible_teachers"
OFFERING_CONSTRAINT_NO_CANDIDATE = "offering_constraint_no_candidate"
OFFERING_SEMESTER_CONSTRAINT_NO_CANDIDATE = "offering_semester_constraint_no_candidate"
SECTION_BUDGET_INFEASIBLE = "section_budget_infeasible"
SEMESTER_CAPACITY_CHANGED_ANNUAL_PLAN = "semester_capacity_changed_annual_plan"
SEMESTER_STAFFING_CAPACITY_SHORTFALL = "semester_staffing_capacity_shortfall"
SHARED_QUALIFIED_STAFFING_POOL_INFEASIBLE = "shared_qualified_staffing_pool_infeasible"
STAFFING_CHANGED_DEMAND_PLAN = "staffing_changed_demand_plan"
TOTAL_STAFFING_CAPACITY_SHORTFALL = "total_staffing_capacity_shortfall"
UNMET_DEMAND_AFTER_STAFFING = "unmet_demand_after_staffing"

# Semester/A-D placement diagnostics. These are stable API/UI contract values;
# detailed wording remains a backend concern and can improve without breaking a
# counselor dashboard.
MISSING_CONFLICT_MATRIX = "missing_conflict_matrix"
ANNUAL_LOCK_OUTSIDE_ANNUAL_COUNT = "annual_lock_outside_annual_count"
LOCKED_TIMESLOT_OUTSIDE_YEAR_OR_SEMESTER = "locked_timeslot_outside_year_or_semester"
SECTION_LOCKED_WITHOUT_USABLE_TIMING = "section_locked_without_usable_timing"
NO_LEGAL_SEMESTER = "no_legal_semester"
NO_AVAILABLE_TIMESLOT = "no_available_timeslot"
NO_ELIGIBLE_TEACHER = "no_eligible_teacher"
TEACHER_AVAILABILITY_COLLISION = "teacher_availability_collision"
TEACHER_SEMESTER_OR_ANNUAL_CAPACITY_SHORTAGE = "teacher_semester_or_annual_capacity_shortage"
ONLINE_SUPERVISION_CAPACITY_INSUFFICIENT = "online_supervision_capacity_insufficient"
ONLINE_SUPERVISION_BLOCK_DIVERSITY_INSUFFICIENT = "online_supervision_block_diversity_insufficient"
NO_COMPLETE_PLACEMENT = "no_complete_placement"

# Named teacher assignment diagnostics are stable API codes.  Views may change
# explanatory prose without forcing frontend clients to parse English text.
MISSING_ACCEPTED_PLACEMENT = "missing_accepted_placement"
NO_ELIGIBLE_TEACHER_FOR_SECTION = "no_eligible_teacher_for_section"
LOCKED_TEACHER_UNAVAILABLE = "locked_teacher_unavailable"
LOCKED_TEACHER_INELIGIBLE = "locked_teacher_ineligible"
TEACHER_TIMESLOT_COLLISION = "teacher_timeslot_collision"
TEACHER_SEMESTER_CAPACITY_SHORTAGE = "teacher_semester_capacity_shortage"
TEACHER_ANNUAL_CAPACITY_SHORTAGE = "teacher_annual_capacity_shortage"
TEACHER_COURSE_RULE_INFEASIBLE = "teacher_course_rule_infeasible"
# Candidate-ledger facts identify why a real roster member could not be used
# for one named staffing decision. They are narrower than stage-level output
# diagnostics such as ``no_eligible_teacher_for_section``.
TEACHER_ASSIGNMENT_QUALIFICATION_UNAVAILABLE = "teacher_assignment_qualification_unavailable"
TEACHER_ASSIGNMENT_TEACHER_UNAVAILABLE = "teacher_assignment_teacher_unavailable"
TEACHER_ASSIGNMENT_EXACT_TEACHER_LOCKED_ELSEWHERE = "teacher_assignment_exact_teacher_locked_elsewhere"
TEACHER_ASSIGNMENT_SEMESTER_CAPACITY_EXHAUSTED = "teacher_assignment_semester_capacity_exhausted"
TEACHER_ASSIGNMENT_ANNUAL_CAPACITY_EXHAUSTED = "teacher_assignment_annual_capacity_exhausted"
TEACHER_ASSIGNMENT_COURSE_RULE_MAXIMUM_REACHED = "teacher_assignment_course_rule_maximum_reached"
NO_COMPLETE_TEACHER_ASSIGNMENT = "no_complete_teacher_assignment"
TEACHER_ASSIGNMENT_INPUT_CHANGED_SINCE_RUN = "teacher_assignment_input_changed_since_run"
TEACHER_ASSIGNMENT_FIXED_CONTEXT_CHANGED_SINCE_RUN = "teacher_assignment_fixed_context_changed_since_run"
FIXED_CONTEXT_CHANGED_SINCE_RUN = "fixed_context_changed_since_run"
PLACEMENT_INPUT_CHANGED_SINCE_RUN = "placement_input_changed_since_run"

# Student assignment diagnostics.  These are machine-readable planning facts,
# not counselor-facing English copy.
# The next-release review contract reserves these names before its solver paths
# exist. Keeping them here prevents services or future API views from creating
# competing literals for client-facing planning facts.
STUDENT_ASSIGNMENT_NO_ACTIVE_PLACED_SECTION = "student_assignment_no_active_placed_section"
STUDENT_ASSIGNMENT_LOCKED_ENROLLMENT_BLOCKS_REQUEST = "student_assignment_locked_enrollment_blocks_request"
STUDENT_ASSIGNMENT_SECTION_BELOW_TARGET_CAPACITY = "student_assignment_section_below_target_capacity"
STUDENT_ASSIGNMENT_SECTION_OVER_TARGET_CONCENTRATION = "student_assignment_section_over_target_concentration"
STUDENT_ASSIGNMENT_LIMITED_SEAT_CONTENTION = "student_assignment_limited_seat_contention"
STUDENT_ASSIGNMENT_REQUIRES_ADDITIONAL_CAPACITY = "student_assignment_requires_additional_capacity"
STUDENT_ASSIGNMENT_REQUIRES_TIMESLOT_CHANGE = "student_assignment_requires_timeslot_change"
STUDENT_ASSIGNMENT_REQUIRES_LOCK_RELEASE = "student_assignment_requires_lock_release"
STUDENT_ASSIGNMENT_REQUIRES_PLACED_SECTION = "student_assignment_requires_placed_section"
STUDENT_ASSIGNMENT_REQUIRES_PREREQUISITE_SEQUENCE_CHANGE = "student_assignment_requires_prerequisite_sequence_change"

STUDENT_ASSIGNMENT_MISSING_ACCEPTED_PLACEMENT = "student_assignment_missing_accepted_placement"
STUDENT_ASSIGNMENT_INVALID_SECTION_CONTEXT = "student_assignment_invalid_section_context"
STUDENT_ASSIGNMENT_NO_ELIGIBLE_SECTION = "student_assignment_no_eligible_section"
STUDENT_ASSIGNMENT_SECTION_CAPACITY_EXHAUSTED = "student_assignment_section_capacity_exhausted"
STUDENT_ASSIGNMENT_TIMESLOT_COLLISION = "student_assignment_timeslot_collision"
STUDENT_ASSIGNMENT_COMBINED_SECTION_COLLISION = "student_assignment_combined_section_collision"
STUDENT_ASSIGNMENT_HARD_PREREQUISITE_CYCLE = "student_assignment_hard_prerequisite_cycle"
STUDENT_ASSIGNMENT_HARD_PREREQUISITE_SEQUENCE_UNAVAILABLE = "student_assignment_hard_prerequisite_sequence_unavailable"
STUDENT_ASSIGNMENT_UNRESOLVED_REQUIRED_REQUEST = "student_assignment_unresolved_required_request"
STUDENT_ASSIGNMENT_AMBIGUOUS_BACKUP_RESOLUTION = "student_assignment_ambiguous_backup_resolution"
STUDENT_ASSIGNMENT_LEGACY_ENROLLMENT_AMBIGUOUS = "student_assignment_legacy_enrollment_ambiguous"
STUDENT_ASSIGNMENT_INPUT_CHANGED_SINCE_RUN = "student_assignment_input_changed_since_run"
STUDENT_ASSIGNMENT_STAFFING_CONTEXT_CHANGED_SINCE_RUN = "student_assignment_staffing_context_changed_since_run"
STUDENT_ASSIGNMENT_INVALID_PROVISIONAL_STAFFING = "student_assignment_invalid_provisional_staffing"
# Special commitments are deliberately separate from ordinary course-section
# diagnostics: an actionable Study, Focus, Co-op, or online-supervision problem
# should never be mistaken for a missing instructional section.
STUDENT_ASSIGNMENT_SPECIAL_COMMITMENT_UNRECOGNIZED = "student_assignment_special_commitment_unrecognized"
STUDENT_ASSIGNMENT_STUDY_LIMIT_EXCEEDED = "student_assignment_study_limit_exceeded"
STUDENT_ASSIGNMENT_NO_COMPATIBLE_ONLINE_SUPERVISION_SESSION = "student_assignment_no_compatible_online_supervision_session"
STUDENT_ASSIGNMENT_ONLINE_SUPERVISION_CAPACITY_EXHAUSTED = "student_assignment_online_supervision_capacity_exhausted"
STUDENT_ASSIGNMENT_NO_VALID_CO_OP_BLOCK_PAIR = "student_assignment_no_valid_co_op_block_pair"
STUDENT_ASSIGNMENT_NO_VALID_FOCUS_SEMESTER = "student_assignment_no_valid_focus_semester"
STUDENT_ASSIGNMENT_SPECIAL_COMMITMENT_LOCK_BLOCKS_REQUEST = "student_assignment_special_commitment_lock_blocks_request"
STUDENT_ASSIGNMENT_HALF_SEMESTER_PAIR_INCOMPLETE = "student_assignment_half_semester_pair_incomplete"
STUDENT_ASSIGNMENT_HALF_SEMESTER_UNALLOCATED_OPPOSITE_HALF = "student_assignment_half_semester_unallocated_opposite_half"
STUDENT_ASSIGNMENT_ONLINE_HALF_SEMESTER_UNUSED_SUPERVISION_HALF = "student_assignment_online_half_semester_unused_supervision_half"
STUDENT_ASSIGNMENT_UNALLOCATED_SCHOOL_TIME = "student_assignment_unallocated_school_time"
NO_COMPLETE_STUDENT_ASSIGNMENT = "no_complete_student_assignment"
