# Generated by Django 6.0.5 on 2026-08-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, 'Fall'), (2, 'Winter')])),
                ('is_available', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'semester', 'day', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.room')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
                ('timeslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.timeslot')),
            ],
            options={
                'ordering': ['section'],
            },
        ),
    ]
