"""Qualification and constraint-domain values.

These values describe the normalized credential system. They intentionally live
outside ``common`` because they are domain policy, not generic school reference
data.
"""

from backend.apps.common.school_values import GRADE_LEVEL_11


QUALIFICATION_REVIEW_PENDING = "pending"
QUALIFICATION_REVIEW_VERIFIED = "verified"
QUALIFICATION_REVIEW_REJECTED = "rejected"
QUALIFICATION_REVIEW_CHOICES = (
    (QUALIFICATION_REVIEW_PENDING, "Pending review"),
    (QUALIFICATION_REVIEW_VERIFIED, "Verified"),
    (QUALIFICATION_REVIEW_REJECTED, "Rejected"),
)

QUALIFICATION_KIND_TEACHABLE = "teachable"
QUALIFICATION_KIND_ADDITIONAL = "additional"
QUALIFICATION_KIND_CHOICES = (
    (QUALIFICATION_KIND_TEACHABLE, "Teachable qualification"),
    (QUALIFICATION_KIND_ADDITIONAL, "Additional qualification"),
)

QUALIFICATION_SUBJECT_NONE = ""
QUALIFICATION_SUBJECT_MATHEMATICS = "mathematics"
QUALIFICATION_SUBJECT_CHEMISTRY = "chemistry"
QUALIFICATION_SUBJECT_FRENCH = "french"
QUALIFICATION_SUBJECT_COMPUTER_STUDIES = "computer_studies"
QUALIFICATION_SUBJECT_BUSINESS_STUDIES_GENERAL = "business_studies_general"
QUALIFICATION_SUBJECT_CHOICES = (
    (QUALIFICATION_SUBJECT_NONE, "Not applicable"),
    (QUALIFICATION_SUBJECT_MATHEMATICS, "Mathematics"),
    (QUALIFICATION_SUBJECT_CHEMISTRY, "Chemistry"),
    (QUALIFICATION_SUBJECT_FRENCH, "French"),
    (QUALIFICATION_SUBJECT_COMPUTER_STUDIES, "Computer Studies"),
    (QUALIFICATION_SUBJECT_BUSINESS_STUDIES_GENERAL, "Business Studies - General"),
)

QUALIFICATION_DIVISION_NONE = "none"
QUALIFICATION_DIVISION_PRIMARY = "primary"
QUALIFICATION_DIVISION_JUNIOR = "junior"
QUALIFICATION_DIVISION_INTERMEDIATE = "intermediate"
QUALIFICATION_DIVISION_SENIOR = "senior"
QUALIFICATION_DIVISION_CHOICES = (
    (QUALIFICATION_DIVISION_NONE, "Not applicable"),
    (QUALIFICATION_DIVISION_PRIMARY, "Primary"),
    (QUALIFICATION_DIVISION_JUNIOR, "Junior"),
    (QUALIFICATION_DIVISION_INTERMEDIATE, "Intermediate"),
    (QUALIFICATION_DIVISION_SENIOR, "Senior"),
)

QUALIFICATION_ENFORCEMENT_REQUIRED = "required"
QUALIFICATION_ENFORCEMENT_PREFERRED = "preferred"
QUALIFICATION_ENFORCEMENT_CHOICES = (
    (QUALIFICATION_ENFORCEMENT_REQUIRED, "Required"),
    (QUALIFICATION_ENFORCEMENT_PREFERRED, "Preferred"),
)
STATUTORY_TEACHABLE_MIN_GRADE = GRADE_LEVEL_11

QUALIFICATION_SOURCE_ASPEN = "aspen"
QUALIFICATION_SOURCE_MANUAL = "manual"
QUALIFICATION_SOURCE_IMPORT = "import"
QUALIFICATION_SOURCE_CHOICES = (
    (QUALIFICATION_SOURCE_ASPEN, "Aspen"),
    (QUALIFICATION_SOURCE_MANUAL, "Manual entry"),
    (QUALIFICATION_SOURCE_IMPORT, "Approved import"),
)

